name: Delete Old Tags

on:
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  delete_old_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch tags
        run: |
          git clone --quiet https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} repo
          cd repo
          git fetch --tags
          git tag | sort -V | head -n -1 > old-tags.txt

      - name: Delete old tags
        run: |
          cd repo
          while read tag; do
            echo "Deleting tag $tag"
            git push origin :refs/tags/$tag
          done < old-tags.txt
          
